### ISSUE TITLE
New solar panels don't get upgraded

### ISSUE THREAD

**Issue by Razunter** [RedRafe/solar-productivity#1]
Solar panels and accumulators are only upgraded after research, new ones have the original stats.
New:
![New](https://github.com/RedRafe/solar-productivity/assets/362900/44d96abb-e34f-4b6b-851e-18210f8bda1d)
Old:
![Old, upgraded](https://github.com/RedRafe/solar-productivity/assets/362900/fe3547ed-2584-4b48-a633-e6a948493b9a)
Tiny debug:
![Debug](https://github.com/RedRafe/solar-productivity/assets/362900/26a8fb9f-a48f-4bb8-9410-002c3f365680)

Main mod: Exotic Industries
Factorio v1.1.82
Mod v0.2.0

[Save](https://www.dropbox.com/s/48vgxklpqkv3k0k/1.1%20Exotic%20Industries.zip?dl=0)

**Comment by RedRafe** [comment]
Hi, thanks for the report.
Unfortunately my computer is not powerful enough to test your savefile & all the mods installed. I re-tested Solar Productivity + Exotic Industry Official Modpack and everything works fine.
The log also seems to have the correct entity registered & the correct build event.

My guess is some other mod is interfering or could it be that you're playing in some cheat/editor/other-strange mode? Anything could help

Thanks

**Comment by Razunter** [comment]
Hm... I play with lots of varied mods.
Tried debugging. It breaks at
```lua
if SOL_PROD.current_level == 0 or not SOL_PROD.DB[old_name] then return end
```
And I think that `SOL_PROD.current_level` is always 0 on save load until you research the next tech.

```lua
function SOL_PROD.on_init()
  if not SOL_PROD.current_level then SOL_PROD.current_level = 0 end
```

**Comment by RedRafe** [comment]
The level should be 0 is no solar Productivity has ever been researched

**Comment by Razunter** [comment]
But I have researched a level. And `on_init` is called on load, I guess. It doesn't check what I have researched.

**Comment by RedRafe** [comment]
Lemme change something, maybe I've found the issue

**Comment by RedRafe** [comment]
Aight, fixed. I forgot to save the state of research. There's probably a better system to do that but it will suffice for the time being just to solve the issue. Further optimizzation will be written eventually but I dont have much time unfortunately.

New release already available on mod portal, lemme know if there are any other issues

Thanks!
