### ISSUE TITLE
Failed to load mods: Error in assignID: item with name 'personal-transformer-output-entity' does not exist.

### ISSUE THREAD

**Issue by Atlntssplayer** [RedRafe/solar-productivity#14]
Hi

I updated two mods in my setup and now I get this error before arriving at the main menu:

```
Failed to load mods: Error in assignID: item with name 'personal-transformer-output-entity' does not exist.

Source: sp-1-personal-transformer-output-entity (accumulator).
Mods to be disabled:
solar-productivity (2.1.1)
```

One of the mods was PersonalTransformer2 and the other was yours, solar-productivity.

I made a few tries to help pin-point the problem:

solar-productivity 2.0.4 loads with either version of PT2 (1.0.8 or 1.0.9).
solar-productivity 2.1.1 DOESNT load with with either version of PersonalTransformer2.
Without any version of PT2 any version of solar-productivity loads.
I can't look at the code because I lack the knowledge.

If you can address thsis issue in your mod please be so kind and look into it.

Thank you!

**Comment by RedRafe** [comment]
Fixed in new release, thank you
